# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5b70e352ca569b20435a14e514cbe88a4e7a5c1be1e223735c076fa003c954882c1608a9ab4ad28e4a27b47cb7b4b72425f240c70e640d0231cd7c273d65145

test:
  secret_key_base: f4180c41430f44904c59c5924b01c5440672085f9304b0f27f6048a5b12cb1fa01d1401478726167f0bce80a931bd1bcb9b2521b924ccb75256d231063667e14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
